#!/bin/bash

n="$1"
prime_count=0
is_prime=1
for (( i=2; i<10000000; i++ )); do
	for (( j=2; j<=i/2; j++ )); do
		if (( i%j==0 )); then
			is_prime=0
			break
		fi
	done
	if (( is_prime == 1 )); then
		prime_count=$(( prime_count + 1 ))
	fi

	if (( prime_count == n )); then
		echo "$i"
		break
	fi
	is_prime=1

done
