#!/bin/bash

restore_dir="$HOME/user/restore"
max_backup_date=""
max_backup_date_sec=0

for dir in $(ls ~/user | grep "Backup-"); do
	current_backup_date=$(echo "$dir" | awk -F'Backup-' '{print $2}')
	current_backup_date_sec=$(date -d "$current_backup_date" +%s)
	if [[ "$current_backup_date_sec" -gt "$max_backup_date_sec" ]]; then
		max_backup_date="$current_backup_date"
		max_backup_date_sec="$current_backup_date_sec"
	fi
done

if [[ max_backup_date == "" ]]; then
	echo "directory does not exist"
fi

backup_dir="$HOME/user/Backup-$max_backup_date"

for file in $(ls "$backup_dir" | grep -v -E ".*\.[0-9]{4}-[0-9]{2}-[0-9]{2}$"); do
	cp "$backup_dir/$file" "$restore_dir"
done
